.TH MYSTRLEN 3 "September 2026" "libmyutils 1.0" "Library Functions Manual"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int mystrlen(const char *" s ");"
.SH DESCRIPTION
The
.B mystrlen()
function calculates the length of the string pointed to by
.I s
excluding the terminating null byte
.RI ( '\\0' ).
.SH RETURN VALUE
The
.B mystrlen()
function returns the number of characters in the string.
.SH AUTHOR
Written by Kanwar Albir Zulfiqar <albirzulfiqar123@gmail.com>
